# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

landmarks_lastfirst_cpp <- function(x, num = 0L, cardinality = 0L, seed_index = 1L, cover = FALSE) {
    .Call('_landmark_landmarks_lastfirst_cpp', PACKAGE = 'landmark', x, num, cardinality, seed_index, cover)
}

landmarks_maxmin_cpp <- function(x, num = 0L, radius = -1, seed_index = 1L, cover = FALSE) {
    .Call('_landmark_landmarks_maxmin_cpp', PACKAGE = 'landmark', x, num, radius, seed_index, cover)
}

maxmin_f <- function(x, eps, n, dist_f, metric = 1L, seed = 0L, pick = 0L, cover = FALSE) {
    .Call('_landmark_maxmin_f', PACKAGE = 'landmark', x, eps, n, dist_f, metric, seed, pick, cover)
}

